name: deploy-manifests

on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2   
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITAL__OCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save takatatick
      - run: kubectl apply -f infra/k8s
